sudo: required

services:
  - docker

before_install:
  - docker build -t liharsw/docker-nginx-react -f Dockerfile.dev .

script:
  - docker run -e CI=true liharsw/docker-nginx-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-061056842369"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"